function licks = importLicks(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LICKS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  LICKS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  licks = importfile("/mnt/lampllab/Ben/Data/Detection task/F102/licks.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Dec-2022 13:10:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Lick", "T1740122227456", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Lick", "T1740122227456"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Lick", "T1740122227456"], "ThousandsSeparator", ",");

% Import the data
licks = readtable(filename, opts);

%% Convert to output type
licks = table2array(licks);
end