function events = importEvents(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EVENTS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  EVENTS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  events = importfile("/mnt/lampllab/Ben/Data/Detection task/F102/events.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Dec-2022 13:06:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Water", "T1740123084416", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Water", "T1740123084416"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Water", "T1740123084416"], "ThousandsSeparator", ",");

% Import the data
events = readtable(filename, opts);

%% Convert to output type
events = table2array(events);
end